# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-07-20 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('theme', models.CharField(max_length=255)),
                ('activity_name', models.CharField(max_length=255)),
                ('activity_description', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('present', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Evaluate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_name', models.CharField(max_length=255)),
                ('assesment_month', models.CharField(max_length=255)),
                ('assessment_level', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'evaluate',
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('mentor_id', models.AutoField(primary_key=True, serialize=False)),
                ('mentor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'mentor',
            },
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('saving_id', models.AutoField(primary_key=True, serialize=False)),
                ('savings', models.IntegerField()),
                ('saving_date', models.DateField()),
            ],
            options={
                'managed': False,
                'db_table': 'saving',
            },
        ),
        migrations.CreateModel(
            name='Stars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=255)),
                ('no_stars', models.IntegerField()),
                ('star_date', models.DateField()),
            ],
            options={
                'managed': False,
                'db_table': 'stars',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_no', models.IntegerField()),
                ('standard', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'student',
            },
        ),
    ]
