# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-07-20 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={},
        ),
    ]
